//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW_Admin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_Account
    {
        [Required]
        [StringLength(25)]
        public string acc_UserID { get; set; }


        [Required]
        [StringLength(25)]
        public string acc_Password { get; set; }
        public Nullable<bool> acc_Active { get; set; }
    }
}
