//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW_Admin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Package
    {
        public tbl_Package()
        {
            this.tbl_FeaturedPackage = new HashSet<tbl_FeaturedPackage>();
            this.tbl_Gallery = new HashSet<tbl_Gallery>();
            this.tbl_PlacePackage = new HashSet<tbl_PlacePackage>();
            this.tbl_Price = new HashSet<tbl_Price>();
        }

        public int pkg_ID { get; set; }

        [Required(ErrorMessage = "Package Name is maindatory.")]
        [StringLength(50, ErrorMessage = "Maximum Allowed length is {1}")]
        public string pkf_Name { get; set; }

        [Required(ErrorMessage = "Subtitle is maindatory.")]
        [StringLength(250, ErrorMessage = "Maximum Allowed length is {1}")]
        public string pkg_Subtitle { get; set; }

        [Required(ErrorMessage = "Overview is maindatory.")]
        public string pkg_Overview { get; set; }

        [Required(ErrorMessage = "Description is maindatory.")]
        public string pkg_Description { get; set; }

        [Required(ErrorMessage = "Inclusione is maindatory.")]
        public string pkg_Inclusion { get; set; }

        public Nullable<bool> pkg_DefaultSeason { get; set; }

        [StringLength(1, MinimumLength = 1, ErrorMessage = "Must be 1, 2 or 3.")]
        [RegularExpression("^1|2|3$", ErrorMessage = "Must be 1, 2 or 3.")]
        public string pkg_DefaultRoom { get; set; }

        [Required(ErrorMessage = "Must be 1, 2 or 3.")]
        [StringLength(1, MinimumLength = 1, ErrorMessage = "Must be 1, 2 or 3.")]
        [RegularExpression("^1|2|3$", ErrorMessage = "Must be 1, 2 or 3.")]
        public string pkg_DefaultDay { get; set; }

        [Required(ErrorMessage = "Day Heading 1 is maindatory.")]
        [StringLength(25, ErrorMessage = "Maximum Allowed length is {1}")]
        public string pkg_DayHeading1 { get; set; }

        [Required(ErrorMessage = "Day Itinerary 1 is maindatory.")]
        public string pkg_DayItinerary1 { get; set; }

        [Required(ErrorMessage = "Day Heading 2 is maindatory.")]
        [StringLength(25, ErrorMessage = "Maximum Allowed length is {1}")]
        public string pkg_DayHeading2 { get; set; }

        [Required(ErrorMessage = "Day Itinerary 2 is maindatory.")]
        public string pkg_DayItinerary2 { get; set; }

        [Required(ErrorMessage = "Day Heading 3 is maindatory.")]
        [StringLength(25, ErrorMessage = "Maximum Allowed length is {1}")]
        public string pkg_DayHeading3 { get; set; }

        [Required(ErrorMessage = "Day Itinerary 3 is maindatory.")]
        public string pkg_DayItinerary3 { get; set; }

        [StringLength(25, ErrorMessage = "Maximum Allowed length is {1}")]
        public string pkg_Roomtype1 { get; set; }

        [StringLength(25, ErrorMessage = "Maximum Allowed length is {1}")]
        public string pkg_Roomtype2 { get; set; }

        [StringLength(25, ErrorMessage = "Maximum Allowed length is {1}")]
        public string pkg_Roomtype3 { get; set; }

        public Nullable<int> pkg_Priority { get; set; }

        public Nullable<bool> pkg_Active { get; set; }

        public string pkg_BannerImage { get; set; }

        public string pkg_SquareImage { get; set; }

        public string pkg_BackgroundImage1 { get; set; }

        public string pkg_BackgroundImage2 { get; set; }

        [Required(ErrorMessage = "Must select some value.")]
        public Nullable<int> pkg_ExclusionFK { get; set; }

        [Required(ErrorMessage = "Must select some value.")]
        public Nullable<int> pkg_TermsAndConditionFK { get; set; }

        [Required(ErrorMessage = "Must select some value.")]
        public Nullable<int> pkg_CancelPolicyFK { get; set; }

        [Required(ErrorMessage = "Must select some value.")]
        public Nullable<int> pkg_SubcategoryFK { get; set; }

        public virtual tbl_CancelPolicy tbl_CancelPolicy { get; set; }
        public virtual tbl_Exclusion tbl_Exclusion { get; set; }
        public virtual ICollection<tbl_FeaturedPackage> tbl_FeaturedPackage { get; set; }
        public virtual ICollection<tbl_Gallery> tbl_Gallery { get; set; }
        public virtual tbl_Subcategory tbl_Subcategory { get; set; }
        public virtual tbl_TermsAndCondition tbl_TermsAndCondition { get; set; }
        public virtual ICollection<tbl_PlacePackage> tbl_PlacePackage { get; set; }
        public virtual ICollection<tbl_Price> tbl_Price { get; set; }
    }
}
