//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW_Admin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_Place
    {
        public tbl_Place()
        {
            this.tbl_Gallery = new HashSet<tbl_Gallery>();
            this.tbl_PlacePackage = new HashSet<tbl_PlacePackage>();
        }

        public int plc_ID { get; set; }

        [Required(ErrorMessage="Place Name is maindatory.")]
        [StringLength(50, ErrorMessage = "Maximum Allowed length is {1}")]
        public string plc_Name { get; set; }
        public string plc_Description { get; set; }

        [StringLength(100, ErrorMessage = "Maximum Allowed length is {1}")]
        public string plc_TimeToVisit { get; set; }

        [StringLength(100, ErrorMessage = "Maximum Allowed length is {1}")]
        public string plc_Location { get; set; }
        public Nullable<int> plc_Priority { get; set; }
        public Nullable<bool> plc_Active { get; set; }
        public string plc_BannerImage { get; set; }
        public string plc_SquareImage { get; set; }
        public string plc_BackgroundImage1 { get; set; }
        public string plc_BackgroundImage2 { get; set; }
    
        public virtual ICollection<tbl_Gallery> tbl_Gallery { get; set; }
        public virtual ICollection<tbl_PlacePackage> tbl_PlacePackage { get; set; }
    }
}
