//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW_Admin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_Category
    {
        public tbl_Category()
        {
            this.tbl_Subcategory = new HashSet<tbl_Subcategory>();
        }
    
        public int cat_ID { get; set; }

        [Required(ErrorMessage="Category Name is Maindatory.")]
        [StringLength(25, ErrorMessage = "Maximum Allowed length is {1}")]
        public string cat_Name { get; set; }
        public string cat_Descripton { get; set; }
        public Nullable<int> cat_Priority { get; set; }
        public Nullable<bool> cat_Active { get; set; }
        public string cat_BannerImage { get; set; }
        public string cat_SquareImage { get; set; }
        public string cat_BackgroundImage1 { get; set; }
        public string cat_BackgroundImage2 { get; set; }
    
        public virtual ICollection<tbl_Subcategory> tbl_Subcategory { get; set; }
    }
}
