//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW_Admin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_Tour
    {
        public int tor_ID { get; set; }

        [Required(ErrorMessage="Tour Name is maindatory.")]
        [StringLength(50, ErrorMessage = "Maximum Allowed length is {1}")]
        public string tor_Name { get; set; }
        public string tor_Overview { get; set; }
        public string tor_Description { get; set; }
        public Nullable<int> tor_Priority { get; set; }
        public Nullable<bool> tor_Active { get; set; }
        public string tor_BannerImage { get; set; }
        public string tor_SquareImage { get; set; }
        public string tor_BackgroundImage1 { get; set; }
        public string tor_BackgroundImage2 { get; set; }
    }
}
