//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PlacePackage
    {
        public int plg_ID { get; set; }
        public int plg_PackageID { get; set; }
        public int plg_PlaceID { get; set; }
    
        public virtual tbl_Package tbl_Package { get; set; }
        public virtual tbl_Place tbl_Place { get; set; }
    }
}
